In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import geopandas as gpd
import math
import numpy as np
import os

/Users/danalapides/opt/miniconda3/lib/python3.9/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.3-CAPI-1.16.1). Conversions between both will be slow.
  warnings.warn(
/var/folders/9h/qhym8j_x3vlby3c3j9klp0vc0000gn/T/ipykernel_7789/3660394021.py:3: DeprecationWarning: Shapely 2.0 is installed, but because PyGEOS is also installed, GeoPandas still uses PyGEOS by default. However, starting with version 0.14, the default will switch to Shapely. To force to use Shapely 2.0 now, you can either uninstall PyGEOS or set the environment variable USE_PYGEOS=0. You can do this before starting the Python process, or in your code before importing geopandas:

import os
os.environ['USE_PYGEOS'] = '0'
import geopandas

In the next release, GeoPandas will switch to using Shapely by default, even if PyGEOS is installed. If you only have PyGEOS installed to get speed-ups, this switch should be smooth. However, if you are using PyGEOS directly (calling PyGEOS functions on geometries from GeoPandas), this will then stop working and you are encouraged to migrate from PyGEOS to Shapely 2.0 (https://shapely.readthedocs.io/en/latest/migration_pygeos.html).
  import geopandas as gpd

In [14]:
# import survey dates
cienega_dates = pd.read_csv('../data/Cienega/Cienega_survey_dates.csv')
# fill nan values with survey dates in left column
cienega_dates['Cienega date'] = np.where(cienega_dates['Cienega date'].isna(),
                                        cienega_dates['mmddyyyy'],
                                        cienega_dates['Cienega date'])
cienega_dates

     mmddyyyy Cienega date  Cienega Length (mi)*
0    6/1/1999    6/28/1999                 2.700
1    6/1/2000     6/1/2000                 2.730
2    6/1/2001    6/26/2001                 4.700
3    9/1/2001    9/18/2001                 5.900
4   12/1/2001   12/14/2001                 5.900
..        ...          ...                   ...
86   6/1/2022     6/3/2022                 3.613
87   9/1/2022     9/8/2022                 5.040
88  12/1/2022   12/15/2022                 6.949
89   3/1/2023    3/10/2023                 7.612
90   6/1/2023     6/8/2023                 5.604

[91 rows x 3 columns]

In [15]:
dataloc = '../data/Cienega/wetdry/' # location where raw data are stored
monthdict = {'Dec':12,'Jan':1,'Feb':2,'Mar':3,
            'Apr':4,'May':5,'Jun':6,'Jul':7,
            'Aug':8,'Sep':9,'Oct':10,'Nov':11,}

# loop through data to convert to geojson files named by survey date
for y in [yy for yy in os.listdir(dataloc) if yy.startswith('2')]:
    for date in [d for d in os.listdir(dataloc+y) if d!='.DS_Store']:
        print(y,date)
        try:
        
            fnames = os.listdir(dataloc+y+'/'+date)
            fname = [f for f in fnames if (f.startswith('ccflow')) and ('all' not in f)]
            surveydata = gpd.read_file(dataloc+y+'/'+date+'/'+fname[0].split('.')[0]+'.shp')
        except:
            try:
                lname = [c for c in os.listdir(dataloc+y+'/'+date) if c!='.DS_Store'][0]
                lname = lname.split('.')[0]
                fnames = os.listdir(dataloc+y+'/'+date+'/'+lname+'/')
                fname = [f for f in fnames if (f.startswith('ccflow')) and ('all' not in f)]
                surveydata = gpd.read_file(dataloc+y+'/'+date+'/'+lname+'/'+fname[0].split('.')[0]+'.shp')
            except:
                lname = [c for c in os.listdir(dataloc+y+'/'+date) if c!='.DS_Store']
                lname = [l for l in lname if (l.startswith('ccflow')) & ('all' not in l) & ('dam' not in l)][0]
                lname = lname.split('.')[0]
                fnames = os.listdir(dataloc+y+'/'+date+'/'+lname+'/')
                fname = [f for f in fnames if (f.startswith('ccflow')) and ('all' not in f)]
                surveydata = gpd.read_file(dataloc+y+'/'+date+'/'+lname+'/'+fname[0].split('.')[0]+'.shp')
                
        # get date of present survey
        mval = monthdict[date.split(' ')[0]] # numerical value associated with given month
        surveydate = cienega_dates[(cienega_dates['Cienega date'].str.contains('/'+y)) & # survey dates for given year only
                      ((cienega_dates['Cienega date'].str.startswith(str(mval))) | # survey dates for given month only
                       (cienega_dates['mmddyyyy'].str.startswith(str(mval))))
                       ]['Cienega date'].values[0]
        surveydate = surveydate.replace('/','-')
        surveydata.to_file(dataloc+'survey_data/'+surveydate+'.geojson', driver="GeoJSON")

2013 Dec 2013
2013 Mar 2013
2013 Jun 2013
2013 Sep 2013
2014 Dec 2014
2014 Mar 2014
2014 Jun 2014
2014 Sep 2014
2022 Dec 2022
2022 Mar 2022
2022 Jun 2022
2022 Sep 2022
2023 Mar 2023
2023 Jun 2023
2015 Dec 2015
2015 Mar 2015
2015 Jun 2015
2015 Sep 2015
2012 Dec 2012
2012 Mar 2012
2012 Jun 2012
2012 Sep 2012
2008 Mar 2008
2008 Dec 2008
2008 Sep 2008
2008 Jun 2008
2001 Dec 2001
2001 Sep 2001
2001 Jun 2001
2006 Mar 2006
2006 Dec 2006
2006 Sep 2006
2006 Jun 2006
2007 Mar 2007
2007 Dec 2007
2007 Sep 2007
2007 Jun 2007
2000 Jun 2000
2009 Mar 2009
2009 Dec 2009
2009 Sep 2009
2009 Jun 2009
2017 Jun 2017
2017 Sep 2017
2017 Dec 2017
2017 Mar 2017
2010 Jun 2010
2010 Sep 2010
2010 Dec 2010
2010 Mar 2010
2019 Jun 2019
2019 Sep 2019
2019 Dec 2019
2019 Mar 2019
2021 Jun 2021
2021 Sep 2021
2021 Dec 2021
2021 Mar 2021
2020 Jun 2020
2020 Sep 2020
2020 Dec 2020
2020 Mar 2020
2018 Jun 2018
2018 Sep 2018
2018 Dec 2018
2018 Mar 2018
2011 Jun 2011
2011 Sep 2011
2011 Dec 2011
2011 Mar 2011
2016 Jun 2016
2016 Sep 2016
2016 Dec 2016
2016 Mar 2016
2005 Sep 2005
2005 Jun 2005
2005 Mar 2005
2005 Dec 2005
2002 Sep 2002
2002 Jun 2002
2002 Mar 2002
2002 Dec 2002
2003 Sep 2003
2003 Jun 2003
2003 Mar 2003
2003 Dec 2003
2004 Sep 2004
2004 Jun 2004
2004 Mar 2004
2004 Dec 2004

In [16]:
# generate geojson for full surveyed region
full_reach = gpd.read_file('../data/Cienega/wetdry/2023/Jun 2023/cclayers0623/ccflow0623_all.shp')
full_reach.to_file('../data/Cienega/surveyReach.geojson',driver='GeoJSON')